import esbuild from "esbuild";
import process from "process";
import os from "os";
import { copyFileSync, existsSync, mkdirSync } from "fs";
import { dirname } from "path";
import builtins from "builtin-modules";
import esbuildSvelte from "esbuild-svelte";
// svelte-preprocess imported lazily inside the plugin config so v6+
// missing-submodule errors don't fail the whole build.

// Auto-deploy the built artifacts into every vault that already has the plugin
// folder, so Hot Reload picks up main.js on each build. A target is skipped if
// its vault (.obsidian) isn't present, so this is safe across machines.
const DEPLOY_TARGETS = [
  "../Sauce_Relationship_Graph/.obsidian/plugins/sauce-crm",
  "../demo-vault/.obsidian/plugins/sauce-crm",
  `${os.homedir()}/Documents/Sauce_Relationship_Graph/.obsidian/plugins/sauce-crm`,
];
const reinstallToSubVault = () => {
  for (const dir of DEPLOY_TARGETS) {
    // Only deploy where the vault exists (the .obsidian parent of the plugin dir).
    if (!existsSync(dirname(dirname(dir)))) continue;
    for (const f of ["main.js", "manifest.json", "versions.json", "styles.css"]) {
      if (existsSync(f)) {
        try { mkdirSync(dirname(`${dir}/${f}`), { recursive: true }); } catch { /* ok */ }
        copyFileSync(f, `${dir}/${f}`);
      }
    }
  }
};

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/`;

const prod = process.argv[2] === "production";

const ctx = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  plugins: [
    // Svelte 5's compiler handles <script lang="ts"> natively, so we
    // skip svelte-preprocess and just point esbuild at the compiler.
    esbuildSvelte({
      compilerOptions: { css: "injected" },
    }),
  ],
  external: [
    "obsidian",
    "electron",
    "@lancedb/lancedb",
    "libsodium-wrappers",
    "argon2-browser",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2020",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await ctx.rebuild();
  reinstallToSubVault();
  process.exit(0);
} else {
  await ctx.watch();
}
