#!/usr/bin/env node
// LM Studio ralph runner — drives a local Qwen model to implement the remaining
// Phase-1 SDK members, gated by typecheck + vitest. Resumable: skips members
// whose .ts already exists, so re-running continues where it left off.
//
// Usage:
//   MODEL="qwen/qwen2.5-coder-14b" node sdk/ralph/lm-runner.mjs
//   MODEL="qwen/qwen3.5-9b" MAX_RETRIES=5 node sdk/ralph/lm-runner.mjs
//
// SECURITY: all process calls use execFileSync with argument arrays (no shell),
// and member group/id are validated against /^[a-z0-9-]+$/ before use — so
// member-derived strings are never parsed by a shell (no command injection).
// Correctness is guaranteed by the gate (nothing red is committed); a member the
// model can't get green within MAX_RETRIES is logged to BLOCKERS.md and skipped.

import { readFileSync, writeFileSync, existsSync, rmSync, appendFileSync, mkdirSync } from 'fs';
import { execFileSync } from 'node:child_process';
import { dirname } from 'path';

const ROOT = process.cwd();
const BASE = process.env.LMS_URL || 'http://localhost:1234/v1';
const MODEL = process.env.MODEL || 'qwen/qwen2.5-coder-14b';
const MAX_RETRIES = Number(process.env.MAX_RETRIES || 4);
const TEMP = Number(process.env.TEMP || 0.15);
const SAFE = /^[a-z0-9-]+$/;

const groupsDir = `${ROOT}/sdk/groups`;
const mPath = (m, ext) => `${groupsDir}/${m.group}/${m.id}.${ext}`;

// No shell: execFile with an argv array. Returns combined stdout; throws on nonzero.
function run(cmd, args) {
  return execFileSync(cmd, args, { cwd: ROOT, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
}
function gate(testFile) {
  for (const [stage, cmd, args] of [
    ['typecheck', 'npm', ['run', '--silent', 'typecheck']],
    ['test', 'npx', ['vitest', 'run', testFile]],
  ]) {
    try {
      run(cmd, args);
    } catch (e) {
      return { ok: false, stage, log: (e.stdout || '') + (e.stderr || '') };
    }
  }
  return { ok: true };
}

async function chat(messages) {
  const res = await fetch(`${BASE}/chat/completions`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ model: MODEL, messages, temperature: TEMP, max_tokens: 4000, stream: false }),
  });
  if (!res.ok) throw new Error(`LM Studio ${res.status}: ${await res.text()}`);
  const json = await res.json();
  return json.choices?.[0]?.message?.content ?? '';
}

// Extract the first fenced code block; if none, return the trimmed text.
function extractCode(text) {
  const m = text.match(/```(?:typescript|ts|javascript|js)?\s*\n([\s\S]*?)```/);
  const body = (m ? m[1] : text).trim();
  return body.endsWith('\n') ? body : body + '\n';
}

// The .md contract is deterministic — templated from the member fields, not the model.
function buildMd(member) {
  return (
    `---\n` +
    `group: ${member.group}\n` +
    `id: ${member.id}\n` +
    `summary: ${member.summary.replace(/\n/g, ' ')}\n` +
    `platform: ${member.platform}\n` +
    `obsidian_api: ${member.obsidian_api}\n` +
    `api_version: "1.8.0"\n` +
    `deterministic: true\n` +
    `depends_on: []\n` +
    `---\n\n` +
    `# ${member.group}/${member.id}\n\n` +
    `${member.summary}\n\n` +
    `Implementation generated by the local-model runner against the mirror member ` +
    `\`${member.mirror}\`, gated by typecheck + vitest.\n`
  );
}

// One file per call → reliable single-code-block output from small models.
function tsPrompt(member, contract, exTs, retryLog) {
  return [
    {
      role: 'system',
      content:
        'Output ONLY a single TypeScript code block (```typescript ... ```), no prose. ' +
        'It must pass `tsc -noEmit -skipLibCheck`. Deterministic: no Date.now/wall-clock in logic. ' +
        'Imports resolve to existing sdk modules (relative paths) or "obsidian".',
    },
    {
      role: 'user',
      content:
        `CONTRACT (excerpt):\n${contract}\n\n` +
        `EXAMPLE (mirror its style) — ${member.mirror}.ts:\n\`\`\`typescript\n${exTs}\`\`\`\n\n` +
        `Implement sdk/groups/${member.group}/${member.id}.ts\n` +
        `obsidian_api=${member.obsidian_api}\nsummary: ${member.summary}\n` +
        (retryLog ? `\nFIX THESE GATE ERRORS:\n${retryLog.slice(0, 2200)}\n` : ''),
    },
  ];
}

function testPrompt(member, genTs, exTest, retryLog) {
  return [
    {
      role: 'system',
      content:
        'Output ONLY a single TypeScript code block, no prose. A vitest test (`import { describe, it, expect } ' +
        "from 'vitest'`) that passes `vitest run`. obsidian.Plugin/Vault/MetadataCache/WorkspaceLeaf are abstract " +
        'in types — instantiate via `new (X as unknown as { new (): X })()`. TFile.contents is stub-only — cast to read it. ' +
        'If obsidian_api is not "none", add a test asserting hasApiSymbol("<symbol>") from "../../generated/api-catalog".',
    },
    {
      role: 'user',
      content:
        `The implementation under test — sdk/groups/${member.group}/${member.id}.ts:\n\`\`\`typescript\n${genTs}\`\`\`\n\n` +
        `EXAMPLE test — ${member.mirror}.test.ts:\n\`\`\`typescript\n${exTest}\`\`\`\n\n` +
        `Write sdk/groups/${member.group}/${member.id}.test.ts. obsidian_api=${member.obsidian_api}.\n` +
        (retryLog ? `\nFIX THESE GATE ERRORS:\n${retryLog.slice(0, 2200)}\n` : ''),
    },
  ];
}

async function doMember(member) {
  if (!SAFE.test(member.group) || !SAFE.test(member.id)) {
    console.log(`SKIP invalid member id/group: ${member.group}/${member.id}`);
    return 'blocked';
  }
  const mdP = mPath(member, 'md');
  const tsP = mPath(member, 'ts');
  const testP = mPath(member, 'test.ts');
  const rel = `sdk/groups/${member.group}/${member.id}`;
  if (existsSync(tsP)) {
    console.log(`SKIP ${member.group}/${member.id} (exists)`);
    return 'skip';
  }
  const contract = readFileSync(`${ROOT}/sdk/CONTRACT.md`, 'utf8').slice(0, 2400);
  const exTs = readFileSync(`${groupsDir}/${member.mirror}.ts`, 'utf8');
  const exTest = readFileSync(`${groupsDir}/${member.mirror}.test.ts`, 'utf8');
  const want = [mdP, tsP, testP];
  let retryLog = '';
  for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
    console.log(`\n[${member.group}/${member.id}] attempt ${attempt}/${MAX_RETRIES} via ${MODEL}`);
    let ts, test;
    try {
      ts = extractCode(await chat(tsPrompt(member, contract, exTs, retryLog)));
      test = extractCode(await chat(testPrompt(member, ts, exTest, retryLog)));
    } catch (e) {
      console.log(`  API error: ${e.message}`);
      retryLog = String(e.message);
      continue;
    }
    mkdirSync(dirname(tsP), { recursive: true });
    writeFileSync(mdP, buildMd(member)); // .md is deterministic, not model-generated
    writeFileSync(tsP, ts);
    writeFileSync(testP, test);
    const g = gate(`${rel}.test.ts`);
    if (g.ok) {
      run('npm', ['run', '--silent', 'sdk:gen']);
      run('git', ['add', mdP, tsP, testP, 'sdk/REGISTRY.md']);
      run('git', ['commit', '-q', '-m', `feat(sdk/${member.group}): ${member.id} — via ${MODEL} (gated)`]);
      console.log(`  ✓ COMMITTED ${member.group}/${member.id}`);
      return 'done';
    }
    console.log(`  ✗ gate failed at ${g.stage}`);
    retryLog = `[${g.stage}]\n${g.log}`;
    for (const w of want) rmSync(w, { force: true }); // revert failed attempt
  }
  appendFileSync(
    `${ROOT}/sdk/ralph/BLOCKERS.md`,
    `- ${member.group}/${member.id}: gate failed after ${MAX_RETRIES} attempts (${MODEL}).\n\n\`\`\`\n${retryLog.slice(0, 1200)}\n\`\`\`\n\n`,
  );
  console.log(`  ⚠ BLOCKED ${member.group}/${member.id} → BLOCKERS.md`);
  return 'blocked';
}

async function main() {
  const queue = JSON.parse(readFileSync(`${ROOT}/sdk/ralph/queue.json`, 'utf8')).members;
  const tally = { done: 0, skip: 0, blocked: 0 };
  console.log(`LM runner: ${queue.length} members, model=${MODEL}, maxRetries=${MAX_RETRIES}`);
  for (const member of queue) {
    const r = await doMember(member);
    tally[r] = (tally[r] || 0) + 1;
  }
  console.log(`\n=== DONE: committed=${tally.done} skipped=${tally.skip} blocked=${tally.blocked} ===`);
}

main().catch((e) => {
  console.error('runner fatal:', e);
  process.exit(1);
});
