// CON-OBS-INTEG-001 · T-F-01 · DEC-006 — runtime introspector + codegen for the
// obsidian-tasks-plugin apiV1.
//
// Two halves, deliberately separated so CI never needs a live vault:
//   1. introspect()  — LIVE: shells `obsidian eval` against a running vault,
//      merges the runtime apiV1 method set with the documented Quick-Reference
//      filter/sort/group/display vocabulary, and writes schemas/obsidian-tasks.json
//      with sorted keys (deterministic). Run manually by a maintainer.
//   2. emitTasksModule(schema) — PURE: deterministic codegen from the committed
//      schema → the sdk/generated/tasks.ts source string. Runs in `sdk:gen`, so
//      `sdk:check` regenerates + diffs it (G-006). No vault, no network.
//
// SECURITY: build/dev tool. Output paths are fixed constants under the project.

import * as fs from "fs";
import { execFileSync } from "child_process";

export interface TasksApiMethod {
  params: string[];
  returns: string;
}
export interface TasksSchema {
  apiV1: Record<string, TasksApiMethod>;
  display: string[];
  filter: string[];
  group: string[];
  sort: string[];
  source?: string;
}

const SCHEMA_PATH = "schemas/obsidian-tasks.json";
const OUT_PATH = "sdk/generated/tasks.ts";

/** Recursively sort object keys so JSON.stringify is byte-stable. */
function sortDeep(value: unknown): unknown {
  if (Array.isArray(value)) return value.map(sortDeep);
  if (value && typeof value === "object") {
    const out: Record<string, unknown> = {};
    for (const k of Object.keys(value as Record<string, unknown>).sort()) {
      out[k] = sortDeep((value as Record<string, unknown>)[k]);
    }
    return out;
  }
  return value;
}

/** A TS string-literal union from a sorted, de-duplicated vocabulary. */
function unionType(name: string, values: string[]): string {
  const uniq = [...new Set(values)].sort();
  const body = uniq.map((v) => `  | ${JSON.stringify(v)}`).join("\n");
  return `export type ${name} =\n${body};`;
}

/** PURE deterministic codegen: schema → sdk/generated/tasks.ts source. */
export function emitTasksModule(schema: TasksSchema): string {
  const methods = Object.keys(schema.apiV1).sort();
  const iface = methods
    .map((m) => {
      const sig = schema.apiV1[m];
      return `  ${m}(${sig.params.join(", ")}): ${sig.returns};`;
    })
    .join("\n");

  return `// GENERATED by sdk/generator/introspect-tasks.ts — DO NOT EDIT.
// Source: ${SCHEMA_PATH} (obsidian-tasks-plugin apiV1 + Quick-Reference vocab).
// Regenerate: npm run sdk:gen. Verified in CI by: npm run sdk:check.

/** The obsidian-tasks-plugin apiV1 surface (auto-enumerated). */
export interface GeneratedTasksApiV1 {
${iface}
}

${unionType("TasksFilter", schema.filter)}

${unionType("TasksSort", schema.sort)}

${unionType("TasksGroup", schema.group)}

${unionType("TasksDisplay", schema.display)}

/** Frozen vocabulary snapshot (for runtime validation / autosuggest). */
export const TASKS_QUERY_VOCAB = {
  filter: ${JSON.stringify([...schema.filter].sort())},
  sort: ${JSON.stringify([...schema.sort].sort())},
  group: ${JSON.stringify([...schema.group].sort())},
  display: ${JSON.stringify([...schema.display].sort())},
} as const;
`;
}

/** Read the committed schema (used by sdk:gen). */
export function loadTasksSchema(path = SCHEMA_PATH): TasksSchema {
  return JSON.parse(fs.readFileSync(path, "utf8")) as TasksSchema;
}

/** Write the generated module (called from generate.ts during sdk:gen). */
export function writeTasksModule(
  schema: TasksSchema,
  outPath = OUT_PATH,
): void {
  fs.writeFileSync(outPath, emitTasksModule(schema)); // nosemgrep -- fixed constant output path
}

/** LIVE introspection: dump the runtime apiV1 method names via `obsidian eval`. */
export function introspectApiV1(): string[] {
  const code =
    "JSON.stringify(Object.keys(app.plugins.plugins['obsidian-tasks-plugin']?.apiV1||{}).sort())";
  const raw = execFileSync("obsidian", [`eval`, `code=${code}`], {
    encoding: "utf8",
  });
  // `obsidian eval` prints `=> <json>`; strip the prefix.
  const json = raw.replace(/^=>\s*/, "").trim();
  return JSON.parse(json) as string[];
}

/** LIVE: re-introspect, reconcile with the committed vocab, rewrite the schema. */
export function introspect(): void {
  const prev = loadTasksSchema();
  const liveMethods = introspectApiV1();
  // Keep documented signatures for known methods; flag any new ones for review.
  const apiV1: Record<string, TasksApiMethod> = {};
  for (const m of liveMethods.sort()) {
    apiV1[m] = prev.apiV1[m] ?? {
      params: ["...args: unknown[]"],
      returns: "unknown",
    };
  }
  const next: TasksSchema = { ...prev, apiV1 };
  fs.writeFileSync(SCHEMA_PATH, JSON.stringify(sortDeep(next), null, 2) + "\n"); // nosemgrep -- fixed path
  writeTasksModule(next);
  // eslint-disable-next-line no-restricted-syntax -- standalone dev CLI, not plugin runtime
  console.log(`[introspect-tasks] apiV1 methods: ${liveMethods.join(", ")}`);
}

// Run introspection only when invoked directly as a CLI.
if (process.argv[1] && /introspect-tasks/.test(process.argv[1])) introspect();
